version: 0.2

phases:
    install:
        commands:
            - go get -u github.com/golang/dep/cmd/dep
    pre_build:
        commands:
            - dep ensure -update
    build:
        commands:
            - make cross-build
artifacts:
    files:
        - bin/**/*
